"""add_ratings

Revision ID: 9f71c8c64a15
Revises: 8590ec36b481
Create Date: 2026-03-02 20:04:02.490821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f71c8c64a15'
down_revision: Union[str, Sequence[str], None] = '8590ec36b481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_player_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player_ratings_match_player')
    )
    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_player_ratings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_player_ratings_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_player_ratings_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_player_ratings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_player_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_player_ratings_player_id'))
        batch_op.drop_index(batch_op.f('ix_match_player_ratings_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_player_ratings_id'))

    op.drop_table('match_player_ratings')
    # ### end Alembic commands ###
